### ISSUE TITLE
The pager persister name should be different 

### ISSUE THREAD

**Issue by makasim** [vadiktok/rabbitmq-elastica-bundle#1]
First, It is great that you liked my ideas and work done on FOSElasticaBundle. Thank you. 

I see one issue here, the pager persister name is the same and if people use both EnqueueElasticaBundle and yours, they would conflict (one of them overwrites the other one).

Could you please change the name. `old_sound_rabbitmq` or just `rabbitmq` sounds good to me.

**Comment by vadikdev** [comment]
Done
Thanks for reporting
